### PR TITLE
Added new fields from ProgrammableWeb.

### PR DESCRIPTION
**Pull request by alexishuf**
Some fields had their writing changed on the HTML, while some of the new fields are too complicated for a table column name. To handle this and renames, a HTML label -> column name map was added together with some small changes on scrapeApiPage().

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@alexishuf 👍

**Comment by IvanGoncharov** [comment]
@alexishuf As a matter of curiosity, how do you use this data?

**Comment by alexishuf** [comment]
@IvanGoncharov I just needed some current (I only had data from a 2010 paper) statistics on the amount of SOAP services vs. (RESTful) Web APIs for the introduction of a paper I'm writing. Probably I wont use it for  anything more as it has lots of outdated stuff and you can't use it as a service repository, as is the case for apis.guru (which I discovered from this scrapper).

**Comment by IvanGoncharov** [comment]
@alexishuf Thanks for the info. If you plan to write other paper about API I have a few interesting datasets to research.  For example here is Google URLs to search for different API consoles:
https://docs.google.com/spreadsheets/d/1O46CwACJQcS-1iWYP1sqP55KPs7ME6r-yoNFiqzvQmk/edit?usp=sharing
Only swagger-ui give almost six thousand results, so it's a lot of data waiting to be scraped 😉 

scraper failed with:
```
Error: SQLITE_ERROR: table apis has 19 columns but 37 values were supplied
     at Error (native)
```
So I clean DB and rerun it.

**Comment by alexishuf** [comment]
@IvanGoncharov genius idea, will keep it in mind.

As for the error, I got confortable with it too quickly. If I need to change columns again, will write an alter table query.

**Pull request merged**
